spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # git仓库配置
          uri: https://github.com/qaz460472353/config-client/
server:
  port: 12010

# 配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/